# A reverse proxy to redirect traffic to a certain host.
---
services:

  proxy:
    image: jc21/nginx-proxy-manager@sha256:e81d01ad119208334ba7adb4986b36ebeb7c727a78732f411e5df84f7c6c50ec
    container_name: reverse-proxy
    hostname: reverse-proxy
    restart: unless-stopped
    networks:
      - proxymesh
    dns:
      - 127.0.0.53                                 # Docker
      - 100.100.100.100                            # Tailscale
      - 1.1.1.1                                    # Cloudflare
    ports:
      - 80:80                                    # HTTPs
      - 443:443                                  # HTTPs
      - 81:81                                    # Admin Web Port
      - 51822:51822                              # port forwarding
      - 25565:25565                              # minecraft 
      # - '21:21'                                  # FTP
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      NODE_OPTIONS: ""
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  proxymesh:
    external: true
    
